# Ores and Flora
bauxite = "bauxite"
caterium_ore = "caterium ore"
coal = "coal"
copper_ore = "copper ore"
crude_oil = "crude oil"
iron_ore = "iron ore"
leaves = "leaves"
limestone = "limestone"
mycelia = "mycelia"
nitrogen_gas = "nitrogen gas"
raw_quartz = "raw quartz"
sam_ore = "sam ore"
sulfur = "sulfur"
uranium = "uranium"
water = "water"
wood = "wood"

# Tier 0
biomass = "biomass"
cable = "cable"
concrete = "concrete"
copper_ingot = "copper ingot"
copper_wire = "copper wire"
fabric = "fabric"
iron_ingot = "iron ingot"
iron_plate = "iron plate"
iron_rod = "iron rod"
reinforced_iron_plate = "reinforced iron plate"
screw = "screw"

#Tier 1
beacon = "beacon"

# Tier 2
copper_sheet = "copper sheet"
modular_frame = "modular frame"
rotor = "rotor"
smart_plating = "smart plating"
solid_biofuel = "solid_biofuel"

# Tier 3
steel_beam = "steel beam"
steel_ingot = "steel ingot"
steel_pipe = "steel pipe"
versatile_framework = "versatile framework"

# Tier 4
automated_wiring = "automated wiring"
encased_industrial_beam = "encased industrial beam"
heavy_modular_frame = "heavy modular frame"
motor = "motor"
stator = "stator"

# Tier 5
adaptive_control_unit = "adaptive control unit"
circuit_board = "circuit board"
compacted_coal = "compacted coal"
computer = "computer"
empty_canister = "empty canister"
fuel = "fuel"
heavy_oil_residue = "heavy oil residue"
liquid_biofuel = "liquid biofuel"
modular_engine = "modular engine"
petroleum_coke = "petroleum coke"
plastic = "plastic"
polymer_resin = "polymer resin"
rubber = "rubber"
turbofuel = "turbofuel"

# Tier 7
alumina_solution = "alumina solution"
aluminum_casing = "aluminum casing"
alclad_aluminum_sheet = "alclad aluminum sheet"
aluminum_scrap = "aluminum scrap"
aluminum_ingot = "aluminum ingot"
assembly_director_system = "assembly director system"
battery = "battery"
crystal_oscillator = "crystal oscillator"
quartz_crystal = "quartz crystal"
radio_control_unit = "radio control unit"
silica = "silica"
sulfuric_acid = "sulfuric acid"

#Tier 8
ai_limiter = "ai limiter"
caterium_ingot = "caterium ingot"
cooling_system = "cooling system"
copper_powder = "copper powder"
electromagnetic_control_rod = "electromagnetic control rod"
empty_fluid_tank = "empty fluid tank"
encased_plutonium_cell = "encased plutonium cell"
encased_uranium_cell = "encased uranium cell"
fused_modular_frame = "fused modular frame"
heat_sink = "heat sink"
high_speed_connector = "high speed connector"
magnetic_field_generator = "magnetic field generator"
nitric_acid = "nitric acid"
non_fissile_uranium = "non-fissile uranium"
nuclear_pasta = "nuclear pasta"
plutonium_fuel_rod = "plutonium fuel rod"
plutonium_pellet = "plutonium pellet"
plutonium_waste = "plutonium waste"
pressure_conversion_cube = "pressure conversion cube"
quickwire = "quickwire"
supercomputer = "supercomputer"
thermal_propulsion_rocket = "thermal propulsion rocket"
turbo_motor = "turbo motor"
uranium_fuel_rod = "uranium fuel rod"
uranium_waste = "uranium waste"
